name: ex08_polymer_contact
description: Contact Manager Apps with Polymer and Dart
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  browser: any
  polymer: '>=0.12.0 <0.16.0'
transformers:
- polymer:
    entry_points: web/ex08_polymer_contact.html
